idf_component_register(SRCS "./crazyflie/hal/src/buzzer.c" 
                "./crazyflie/hal/src/freeRTOSdebug.c" 
                "./crazyflie/hal/src/ledseq.c" 
                "./crazyflie/hal/src/pm_esplane.c" 
                "./crazyflie/hal/src/sensors_mpu6050_hm5883L_ms5611.c" 
                "./crazyflie/hal/src/sensors.c" 
                "./crazyflie/hal/src/usec_time.c" 
                "./crazyflie/hal/src/wifilink.c"
                "./crazyflie/modules/src/app_handler.c" 
                "./crazyflie/modules/src/app_channel.c" 
                "./crazyflie/modules/src/attitude_pid_controller.c"
                "./crazyflie/modules/src/comm.c"
                "./crazyflie/modules/src/commander.c"
                "./crazyflie/modules/src/console.c"
                "./crazyflie/modules/src/controller_indi.c"
                "./crazyflie/modules/src/controller_mellinger.c"
                "./crazyflie/modules/src/controller_pid.c"
                "./crazyflie/modules/src/controller.c"
                "./crazyflie/modules/src/crtp_commander_generic.c"
                "./crazyflie/modules/src/crtp_commander_high_level.c"
                "./crazyflie/modules/src/crtp_commander_rpyt.c"
                "./crazyflie/modules/src/crtp_commander.c"
                "./crazyflie/modules/src/crtp.c"
                "./crazyflie/modules/src/crtpservice.c"
                "./crazyflie/modules/src/estimator_complementary.c"
                "./crazyflie/modules/src/estimator_kalman.c"
                "./crazyflie/modules/src/estimator.c"
                "./crazyflie/modules/src/kalman_core.c"
                "./crazyflie/modules/src/kalman_supervisor.c"
                "./crazyflie/modules/src/log.c"
                "./crazyflie/modules/src/mem.c"
                "./crazyflie/modules/src/msp.c"
                "./crazyflie/modules/src/outlierFilter.c"
                "./crazyflie/modules/src/param.c"
                "./crazyflie/modules/src/pid.c"
                "./crazyflie/modules/src/planner.c"
                "./crazyflie/modules/src/platformservice.c"
                "./crazyflie/modules/src/position_controller_indi.c"
                "./crazyflie/modules/src/position_controller_pid.c"
                "./crazyflie/modules/src/position_estimator_altitude.c"
                "./crazyflie/modules/src/power_distribution_stock.c"
                "./crazyflie/modules/src/pptraj_compressed.c"
                "./crazyflie/modules/src/pptraj.c"
                "./crazyflie/modules/src/queuemonitor.c"
                "./crazyflie/modules/src/range.c"
                "./crazyflie/modules/src/sensfusion6.c"
                "./crazyflie/modules/src/sitaw.c"
                "./crazyflie/modules/src/sound_cf2.c"
                "./crazyflie/modules/src/stabilizer.c"
                "./crazyflie/modules/src/flight_ready_state.c"
                                "./crazyflie/modules/src/sysload.c"
                "./crazyflie/modules/src/system.c" 
                "./crazyflie/modules/src/altitude_logger.c"
                "./crazyflie/modules/src/autonomous_position_hold.c"
                "./crazyflie/modules/src/motor_diagnostic.c"
                "./crazyflie/modules/src/gyro_calibration.c"
                "./crazyflie/modules/src/auto_calibration_ai.c"
                "./crazyflie/modules/src/trigger.c"
                "./crazyflie/modules/src/worker.c"
                "./crazyflie/utils/src/abort.c"
                "./crazyflie/utils/src/cfassert.c"
                "./crazyflie/utils/src/clockCorrectionEngine.c"
                "./crazyflie/utils/src/configblockeeprom.c"
                "./crazyflie/utils/src/cpuid.c"
                "./crazyflie/utils/src/crc_bosch.c"
                "./crazyflie/utils/src/crc.c"
                "./crazyflie/utils/src/debug_cf.c"
                "./crazyflie/utils/src/eprintf.c"
                "./crazyflie/utils/src/filter.c"
                "./crazyflie/utils/src/FreeRTOS-openocd.c"
                "./crazyflie/utils/src/num.c"
                "./crazyflie/utils/src/sleepus.c"
                "./crazyflie/utils/src/statsCnt.c"
                "./crazyflie/utils/src/version.c"
                "./crazyflie/utils/src/rateSupervisor.c"
                INCLUDE_DIRS "./crazyflie/hal/interface" "./crazyflie/modules/interface" "./crazyflie/utils/interface"
                REQUIRES i2c_bus deck mpu6050 ms5611 hmc5883l pmw3901 vl53l1 vl53l0 platform config led eeprom dsp_lib motors wifi adc esp_timer leader_comm web_server)

idf_component_get_property( FREERTOS_ORIG_INCLUDE_PATH freertos ORIG_INCLUDE_PATH)
target_include_directories(${COMPONENT_TARGET} PUBLIC
  "${FREERTOS_ORIG_INCLUDE_PATH}"
)
target_compile_options(${COMPONENT_LIB} PRIVATE "-fno-strict-aliasing"
                                                "-Wno-error=stringop-truncation"
                                                "-Wno-absolute-value"
                                                "-Wno-address-of-packed-member"
                                                "-Wno-stringop-truncation")